/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import java.io.IOException;

/**
 * This is where the server starts
 */
public class App {

    /**
     * Main function: run the server
     * @param args
     * @throws IOException
     */
    public static void main(String[] args) throws IOException {
        Server server = new Server(12345);
        server.run();
    }
}
